version = 5.1.0
archive_dir = /etc/letsencrypt/archive/admin.rjpasseios.com.br
cert = /etc/letsencrypt/live/admin.rjpasseios.com.br/cert.pem
privkey = /etc/letsencrypt/live/admin.rjpasseios.com.br/privkey.pem
chain = /etc/letsencrypt/live/admin.rjpasseios.com.br/chain.pem
fullchain = /etc/letsencrypt/live/admin.rjpasseios.com.br/fullchain.pem
[renewalparams]
account = f5a88d100b89e533a389c91018280af0
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
